identityTrustAnchorsPEM: |
  -----BEGIN CERTIFICATE-----
  MIIFKzCCAxOgAwIBAgIUJOQxs9stjnZlm/3E7Xm9Qd6uSQ0wDQYJKoZIhvcNAQEL
  BQAwJTEjMCEGA1UEAwwacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjYw
  NzAyMDMyOTU5WhcNMzYwNjI5MDMyOTU5WjAlMSMwIQYDVQQDDBpyb290Lmxpbmtl
  cmQuY2x1c3Rlci5sb2NhbDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
  AIoNHZuYoPrbtYprnf05VW5Y9LiqJRpyr7tWUeE4z7Qv0C0kVL1zcPf04bLd1FgP
  0KBSTuhYRCREJUmJkCeTGXcWU3zb0emFUN+yVPxLjuCQfsTN5BeO4r6MyW7ilvzJ
  U3ELvDGQvg44zB3FOmS+sssZvykeqiktn5db3FbL+uOw08rmqL5voxxDwGYMXRZq
  5ikNzJKDPyl7dvyGx2N4rNqdAXgf/G0ZOB8q6jNHm21gDCuUcgGM0iSzNSOpNzDj
  OWl7lj5+7vVetGwNYwXXisVuSZq6uJP0oDHM79vhuRHjRjRIRfVQoY3c/wNWHS1o
  4YaeLmcmLP/1g8AP6a/HK0BAr6B+MzMvKqSMrnvJCIGSyQWGXIzNxBXbiWjCVb/E
  4Hic9iEQNMwvE89p3rYbOmGQtnwbLlgFQTitjDAuKFYn8beyi8VU0NS7GGVQ9ggs
  nDnGHadTZGivggsje5873V/FtdGxNwyXBLS0EvN+EJBUZu8tiVj0FsNdDcO/FP8U
  SZFiUymKyZSiWv4UFRhRqG6XniQpnmesu+gqIOQ/DtYXQ2FBg2qa5FHwmG+E1bzp
  11F8NXfw+WFdT/aVfTxpudv3dfEEA5EFKIVyt4vy1k7EjCCGSmQDv48DWCbSGZup
  FZ/7jFngTri48in4Tw+zKb31cCSjBY1B7R2mYETA0fC9AgMBAAGjUzBRMB0GA1Ud
  DgQWBBT316fAlj8hYlWlAKs3+cR/yXg3jzAfBgNVHSMEGDAWgBT316fAlj8hYlWl
  AKs3+cR/yXg3jzAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4ICAQBp
  Ud3adA90KhYAEO+txUxh5excIzdwYiQ3snKSfk94opKIqXlBIIS870I+4G+5EDNY
  4lazrG/LzirgPKt060HfNyqFXQ9BIA3VsYr5pgxQ8LDL3XJitIuI4tB8u1IVHqvM
  HF4XGhUWEnPebG295oKdhDYF4+IaeNvsYJL0pqRpQ5P3d3zHjREZtKCg/Ex4wfNm
  KnbvZxDLCV73BT+WCLCZ3urcfr6FOJgaPKdRYvFd0zSlg7wJi63xTunvJyhS8+es
  I5a3jiSehJAiLcf4wrh/U729pgLDlh9btlwU5YQnwS0E4SvnZK1APf4nw4ijGLvq
  klwxTHZgN2O6n9YqUDFB8n0bNqWjrEkMcTrSisSSM7PvXe75z8ZirLGbcOyjay7N
  DBZaNahw5FjbIvUQimsAVmjQHaFPBv/z2hi0vBAFnEOKiCuTg0iMDigYP6qcz/Ab
  x3gg+2gQAwtFYoHYCeAlENlSS6bQBGLVvm7lYVXGfnzrVigFAB44WiJIErsyKiwg
  QmbTOUIHm3vo2Q/8GfMBbLQZyjXJW5meyrILB+Jn4GKdmAvV8/iqqIs/PA27exMs
  Fu/MnFPNxL4Dh97YJMfNF2Oh5Rhenb/rXLaUFxpgf5vINVnyNbVb2ojZhGnprLEn
  EsPwV7Tyxi+MLEwvwLTJtoUhO++YIKwgADviokNgwA==
  -----END CERTIFICATE-----

identity:
  issuer:
    scheme: kubernetes.io/tls
