apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.ServiceName}}
  labels:
    app: {{.ServiceName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.ServiceName}}
  template:
    metadata:
      labels:
        app: {{.ServiceName}}
    spec:
      containers:
        - name: app
          image: lokiforce-dev/{{.ServiceName}}:latest
          ports:
            - containerPort: {{.Port}}
          env:
            - name: PORT
              value: "{{.Port}}"
