apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: observability
  labels:
    app: clickhouse
spec:
  ports:
    - name: http
      port: 8123
      targetPort: 8123
    - name: tcp
      port: 9000
      targetPort: 9000
  selector:
    app: clickhouse
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: observability
  labels:
    app: clickhouse
spec:
  serviceName: clickhouse
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:24.3-alpine
          ports:
            - name: http
              containerPort: 8123
            - name: tcp
              containerPort: 9000
          env:
            - name: CLICKHOUSE_DB
              value: lokiforce
            - name: CLICKHOUSE_USER
              value: clickhouse
            - name: CLICKHOUSE_PASSWORD
              value: clickhouse123
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: clickhouse-data
              mountPath: /var/lib/clickhouse
      volumes:
        - name: clickhouse-data
          emptyDir: {}

