apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  git.credentials: |
    secret: argocd/gitops-git-creds
  registries.conf: |
    registry:ghcr.io
      api_url: https://ghcr.io
      credentials: secret:argocd/ghcr-registry-secret
      ping: true
